export interface Device {
    id: number;
    name: string;
    imei: string;
    model_nr: number;
    deviceshow: number;
    protokoll: any | null;
    devicezeit: any | null;
    modellid: any | null;
    telefonnummer: any | null;
    kategorie: any | null;
    speicherdauer: number;
    intervalllaenge: number;
    status: number;
    package: any | null;
    createdate: any | null;
    updatedate: any | null;
    spuraktiv: number;
    alarmintervall: number;
    spurmodus: number;
    spurfarbe: string;
    spurpunkte: number;
    spurminuten: number;
    spurdatum: number;
    spurdatumbis: number;
    spursymbolbewegung: number;
    spursymbolpause: number;
    alarmeinstellungenglobal: number;
    alarmbewegung: number;
    alarmbewegungintervall: number;
    alarmgeschwindigkeit: number;
    alarmgeschwindigkeitab: number;
    alarmgeschwindigkeitintervall: number;
    alarmgeozaunbefahren: number;
    alarmgeozaunbefahrenintervall: number;
    alarmgeozaunverlassen: number;
    alarmgeozaunverlassenintervall: number;
    alarmakkuwarnung: number;
    alarmakkuwarnungab: number;
    alarmakkuwarnungintervall: number;
    alarmzuendalarm: number;
    alarm_turn_off: number;
    alarm_volt: number;
    alarm_volt_value: string;
    guard_id: any | null;
    alarmstromunterbrechung: number;
    tagesemail: number;
    alarmbewegunglastmail: number;
    alarmgeschwindigkeitlastmail: number;
    alarmgeozaunbefahrenlastmail: number;
    alarmgeozaunverlassenlastmail: number;
    alarmakkuwarnunglastmail: number;
    alarmakkucounter: number;
    alarmstromunterbrechunglastmail: number;
    alarmzuendalarmlastmail: number;
    alarmzuendalarmlastmailon: number;
    alarmzuendalarmlastmailoff: number;
    iconname: string;
    iconusecustom: number;
    iconcustomimage: any | null;
    radius_meter: number;
    radius_lat: any | null;
    radius_lng: any | null;
    radius_laststatus: number;
    geschwindigkeit_laststatus: number;
    zuend_laststatus: number;
    acc_lastdateunix: number;
    alarmsos: number;
    alarmsoslastmail: number;
    last_dateunix: any | null;
    last_datum: any | null;
    last_uhrzeit: any | null;
    last_lat_symbol: any | null;
    last_lng_symbol: any | null;
    show_kmanzeige: number;
    show_gruppenanzeigeanzeige: number;
    last_serviceport: number;
    stats_speed_active: number;
    timezone: string;
    create_dateunix: number;
    create_dateunix_str: any | null;
    auto_upd_date: string;
    ac_status: number;
    average_consum: string;
    selected_date_range: string;
    car_id: any | null;
    private_mode: number;
    carDevice_id: any | null;
    alarm_geofence: number;
    setup_done: boolean;
    privacy_mode: number;
    share_link: boolean;
    loadroute: number;
    note: any | null;
    note_color: any | null;
    threedModel_name: any | null;
    threedModel_color: any | null;
    deleted_at: any | null;
    category_id: any | null;
    alarm_enabled: number;
    live_tracking_start_time: any | null;
    live_tracking_duration: any | null;
    logbook_access: number;
    route_profile: string[];
    route_accuracy: any | null;
    activity_daily_goal: any | null;
    customImgUrl: string;
    devicepos: {
        lon: number;
        lat: number;
    };
    last_position: {
        longitude: number;
        latitude: number;
    };
}